name: AdBlock Filter Compiler

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  generate_adblock_filters:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --no-cache-dir requests

      - name: Run filter generator script
        run: python adblock_filter_compiler.py

      - name: Commit and push updated filter list
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add *.txt
            git commit -m "chore: update filter list [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
